### ISSUE TITLE
Can't use keybind when reading a book.

### ISSUE THREAD

**Issue by Saile69** [Coderx-Gamer/ui-utils#103]
Was testing a dupe. Problem is that when I'm in game reading a book (this is a needed step for the dupe), you can't access your saved GUI with the keybind. You've gotta close out of the book first in order for you to be able to use the keybind again. Just wondering if it's possible to make it so we'd be able to use our saved GUI when interacting with books. 
![image](https://github.com/Coderx-Gamer/ui-utils/assets/114521456/09004369-b266-469c-8e70-3961de732258)

Image for clarity.

**Comment by Coderx-Gamer** [comment]
It isn't really meant to be used inside GUIs, it is only useful if you are 'ghost closing' the GUI because if you open a new one the server will invalidate it. For your case, books aren't considered a 'GUI' on the server because it is only on your client. If you want to modify books while going to a new GUI, try modifying UI-Utils or making your own mod for it.

**Comment by MrBreakNFix** [comment]
Not planned for now, but we will think about it
